title: Adelyn Liu  
#logo: /assets/img/headshot_circle.png
description: MS in Business Analyst, 2-year experience as a data analyst in insurance, education, and E-commerce industries.
#theme: jekyll-theme-minimal
remote_theme: pages-themes/modernist@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
